### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [DelightRun/cuPathTracer#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/116842445-2d558b80-ac0f-11eb-85e4-9e0eb122f7e4.png)

thank you  
best regards to you  
William

**Comment by DelightRun** [comment]
Maybe caused by std::flush. I removed all std::flush, please pull the latest code and try again.
Contact me again if the error still occurs.
